CREATE TABLE IF NOT EXISTS TEACHER (
    ID SERIAL PRIMARY KEY
  , NAME VARCHAR(128) NOT NULL
  , LOGIN_ID VARCHAR(128) NOT NULL
  , UNIQUE(LOGIN_ID)
);
CREATE TABLE IF NOT EXISTS CLASSROOM (
    ID SERIAL PRIMARY KEY
  , NAME VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS STUDENT(
    ID SERIAL PRIMARY KEY
  , NAME VARCHAR(128) NOT NULL
  , LOGIN_ID VARCHAR(128) NOT NULL
  , UNIQUE(LOGIN_ID)
);

CREATE TABLE IF NOT EXISTS TEACHER_CLASSROOM (
    TEACHER_ID INTEGER NOT NULL
        REFERENCES TEACHER(ID)
  , CLASSROOM_ID INTEGER NOT NULL
        REFERENCES CLASSROOM(ID)
  , UNIQUE (TEACHER_ID, CLASSROOM_ID)
);
CREATE TABLE IF NOT EXISTS CLASSROOM_STUDENT (
  CLASSROOM_ID INTEGER NOT NULL
        REFERENCES CLASSROOM(ID)
  , STUDENT_ID INTEGER NOT NULL
        REFERENCES STUDENT(ID)
  , UNIQUE (CLASSROOM_ID, STUDENT_ID)
);
