INSERT INTO TEACHER_CLASSROOM (TEACHER_ID, CLASSROOM_ID)
SELECT t.ID, c.ID
FROM (
    SELECT ID
    FROM TEACHER
    ORDER BY ID ASC
    LIMIT 1 OFFSET 0
) as t
CROSS JOIN (
    SELECT ID
    FROM CLASSROOM
    ORDER BY ID ASC
    LIMIT 3 OFFSET 0
) as c
;
INSERT INTO TEACHER_CLASSROOM (TEACHER_ID, CLASSROOM_ID)
SELECT t.ID, c.ID
FROM (
    SELECT ID
    FROM TEACHER
    ORDER BY ID ASC
    LIMIT 1 OFFSET 1
) as t
CROSS JOIN (
    SELECT ID
    FROM CLASSROOM
    ORDER BY ID ASC
    LIMIT 1 OFFSET 3
) as c
;
INSERT INTO TEACHER_CLASSROOM (TEACHER_ID, CLASSROOM_ID)
SELECT t.ID, c.ID
FROM (
    SELECT ID
    FROM TEACHER
    ORDER BY ID ASC
    LIMIT 1 OFFSET 2
) as t
CROSS JOIN (
    SELECT ID
    FROM CLASSROOM
    ORDER BY ID ASC
    LIMIT 1 OFFSET 4
) as c
;
INSERT INTO TEACHER_CLASSROOM (TEACHER_ID, CLASSROOM_ID)
SELECT t.ID, c.ID
FROM (
    SELECT ID
    FROM TEACHER
    ORDER BY ID ASC
    LIMIT 1 OFFSET 3
) as t
CROSS JOIN (
    SELECT ID
    FROM CLASSROOM
    ORDER BY ID ASC
    LIMIT 1 OFFSET 0
) as c
;

