INSERT INTO CLASSROOM_STUDENT (CLASSROOM_ID, STUDENT_ID)
SELECT c.ID, s.ID
FROM (
    SELECT ID
    FROM CLASSROOM
    ORDER BY ID ASC
    LIMIT 1 OFFSET 0
) as c
CROSS JOIN (
    SELECT ID
    FROM STUDENT
    ORDER BY ID ASC
    LIMIT 10 OFFSET 0
) as s
;
INSERT INTO CLASSROOM_STUDENT (CLASSROOM_ID, STUDENT_ID)
SELECT c.ID, s.ID
FROM (
    SELECT ID
    FROM CLASSROOM
    ORDER BY ID ASC
    LIMIT 1 OFFSET 1
) as c
CROSS JOIN (
    SELECT ID
    FROM STUDENT
    ORDER BY ID ASC
    LIMIT 5 OFFSET 10
) as s
;
INSERT INTO CLASSROOM_STUDENT (CLASSROOM_ID, STUDENT_ID)
SELECT c.ID, s.ID
FROM (
    SELECT ID
    FROM CLASSROOM
    ORDER BY ID ASC
    LIMIT 1 OFFSET 3
) as c
CROSS JOIN (
    SELECT ID
    FROM STUDENT
    ORDER BY ID ASC
    LIMIT 5 OFFSET 15
) as s
;
